name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        deno: ["v1.x", "canary"]
        os: [macOS-latest, windows-latest, ubuntu-latest]
        include:
        - os: ubuntu-latest
          path: ~/.cache/deno/
        - os: macos-latest
          path: ~/Library/Caches/deno/
        - os: windows-latest
          path: ~\AppData\Local\deno\

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}

      - name: Verify formatting
        if: startsWith(matrix.os, 'ubuntu') && matrix.deno == 'v1.x'
        run: deno fmt --check

      - name: Run linter
        if: startsWith(matrix.os, 'ubuntu') && matrix.deno == 'canary'
        run: deno lint

      - name: Spell-check
        if: startsWith(matrix.os, 'ubuntu') && matrix.deno == 'canary'
        uses: crate-ci/typos@master

      - name: Type check project
        run: deno task check:types

      - name: Cache dependencies
        if: startsWith(matrix.os, 'ubuntu') && matrix.deno == 'v1.x'
        run: deno cache --config=www/deno.json src/dev/deps.ts src/server/deps.ts www/main.ts  

      - name: Cache Chrome
        uses: actions/cache@v3
        with:
          path: ${{ matrix.path }}deno_puppeteer
          key: chrome-1022525-${{ runner.os }}-${{ hashFiles('tests/deps.ts') }}

      - name: Install Chromium (Unix)
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'mac')
        run: PUPPETEER_PRODUCT=chrome deno run -A --unstable https://deno.land/x/puppeteer@16.2.0/install.ts

      - name: Install Chromium (Windows)
        if: startsWith(matrix.os, 'windows')
        run: set "PUPPETEER_PRODUCT=chrome" && deno run -A --unstable https://deno.land/x/puppeteer@16.2.0/install.ts

      - name: Run tests
        run: deno test -A

      - name: Type check init script
        run: deno check --remote init.ts

      - name: Test website
        run: deno test -A
        working-directory: www/

      - name: Type check demo
        run: deno check --remote main.ts dev.ts
        working-directory: demo